# Generated by Django 5.1.7 on 2025-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='body',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='emp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='luck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='move',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='character',
            name='tech',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='will',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
