# Generated by Django 5.1.7 on 2025-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_character_body_character_cool_character_dex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='body',
        ),
        migrations.RemoveField(
            model_name='character',
            name='cool',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dex',
        ),
        migrations.RemoveField(
            model_name='character',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='character',
            name='int',
        ),
        migrations.RemoveField(
            model_name='character',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='character',
            name='move',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='character',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='character',
            name='will',
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
