# Generated by Django 5.1.7 on 2025-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_character_body_remove_character_cool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.JSONField(default=dict),
        ),
    ]
