# Generated by Django 5.1.7 on 2025-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_character_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
    ]
