# Generated by Django 5.1.7 on 2025-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='role_level',
            field=models.IntegerField(default=1),
        ),
    ]
