# Generated by Django 5.1.7 on 2025-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_character_role_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
