# Generated by Django 5.1.7 on 2025-04-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_character_abilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='abilities',
            new_name='ability',
        ),
    ]
