# Generated by Django 5.1.7 on 2025-04-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_abilities_character_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hum',
            field=models.IntegerField(default=0),
        ),
    ]
