# Generated by Django 5.1.7 on 2025-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_character_hum'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cyberware',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='vehicle',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
